server:
  port: 9090
  error:
    include-stacktrace: never
    include-message: always

spring:
  application:
    name: demo-rest-service

eureka:
  instance:
    appname: demo-rest-service
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
